# If true, will renumber workspaces in every groups so that they are in
# numerical order, similar to tmux's `renumber-windows` option.
renumber_workspaces = false

[workspace_moves]
# If a workspace is moved to another group which already has a workspace with
# the same number, use the next available number instead of failing.
use_next_available_number = false

[icons]
# If true, show window icons in the workspace name.
enable = true
# By default, icons are only shown for workspaces in the active group. If you
# set this to true, icons will be shown for all the workspaces.
enable_all_groups = true
# Delimiter for multiple icons.
delimiter = ' '
# Prefix and suffix to add the the shown icons. Useful for adding spaces in
# fonts that cause icons to overlap with nearby characters.
prefix = ''
suffix = ''
# Minimum number of duplicate icons in a workspace for them to show as Nx<icon>
min_duplicates_count = 5
# The icon used when no rule matches. Set to the empty string to disable showing
# any icon when no rule matches.
default_icon = ''
# If true and none of the rules in the config match the window, will try a set
# of fallback rules before finally falling back to the default icon.
try_fallback_rules = true

# Other relevant glyphs:
# îƒ ï® ï‰©
# ï…ª ï…¦ ï…§ ï…« îœ± îœ‰ ïŠ– ï‰© ïƒ  ïŠ¶ ïŸˆ ï¥Œïƒ¥ ïƒ¦ ï¾ ï‚› ï‹† ï‡— ï‰¦
# ï‡¬ ï›‚ ïƒ€ îˆ îˆµ ï‹ ï€“ ï„  î˜«
# ï¢ƒ ï¢„ ï¢… ï¢† ï¢‡ ï¢ˆ ï¢‰ ï¢Š ï’… ï©½ ï©¾ ï©¿ ïª€
# ïŸ¨ ïŸ© ïŸª ïŸ« ïŸ¬ ïŸ­ ïŸ® î˜
# îœ ï˜› ï˜œ ï˜ ï˜ ï˜Ÿ
# ï‡¸ ïš¿
# ï¡¤ ï¡¥ ï¡¦ ï¡§ ï¡¨ ï¡© ï‚†
# https://fontawesome.com/icons/weixin?style=brands


# === Terminal BEGIN ===
[[icons.rules]]
property = 'title'
match = '/usr/bin/nvim\b.*'
icon = 'îŸ…'
[[icons.rules]]
property = 'title'
match = 'CALCULATOR'
icon = 'ï‡¬'
[[icons.rules]]
property = 'title'
match = '\branger\b'
icon = 'î—¾'

[[icons.rules]]
property = 'class'
match = 'kitty|Alacritty|Termite|URxvtc?'
icon = 'î•'
# === Terminal END ===

# === Browser BEGIN ===
[[icons.rules]]
property = 'title'
match = '.*\bYouTube â€” Mozilla Firefox'
icon = 'ï…ª'
[[icons.rules]]
property = 'title'
match = 'Google ç¿»è¯‘ â€” Mozilla Firefox'
icon = 'ï¾'

[[icons.rules]]
property = 'title'
match = 'å¾®ä¿¡ç½‘é¡µç‰ˆ â€” Mozilla Firefox'
icon = 'ï‡—'
[[icons.rules]]
property = 'title'
match = 'Telegram Web â€” Mozilla Firefox'
icon = 'ï‹†'
[[icons.rules]]
property = 'title'
match = '.*\b - ç»´åŸºç™¾ç§‘ï¼Œè‡ªç”±çš„ç™¾ç§‘å…¨ä¹¦ â€” Mozilla Firefox'
icon = 'ï‰¦ '
[[icons.rules]]
property = 'title'
match = '.*\b - Wikipedia â€” Mozilla Firefox'
icon = 'ï‰¦'

[[icons.rules]]
property = 'title'
match = 'GitHub â€” Mozilla Firefox'
icon = 'ï‚›'



[[icons.rules]]
property = 'class'
match = '[Ff]irefox'
icon = 'î…'

[[icons.rules]]
property = 'class'
match = 'Chromium|Chrome'
icon = 'îƒ'

# === Browser END ===


[[icons.rules]]
property = 'class'
match = '.*wechat.exe.*'
icon = 'ï‡—'
[[icons.rules]]
property = 'class'
match = 'netease-cloud-music'
icon = 'ï€'

[[icons.rules]]
property = 'class'
match = 'Nemo'
icon = 'î—¾'

[[icons.rules]]
property = 'class'
match = 'Rofi'
icon = 'ï„ '

[[icons.rules]]
property = 'class'
match = 'Zotero'
icon = 'â›'


[[icons.rules]]
property = 'title'
match = '.*\bn?TIM\b'
icon = 'ğŸ§'


[[icons.rules]]
property = 'class'
match = 'copyq'
icon = 'ïƒª'

[[icons.rules]]
property = 'class'
match = 'Pqiv'
icon = 'î‰„'

[[icons.rules]]
property = 'class'
match = 'Pinta'
icon = 'îˆ«'

[[icons.rules]]
property = 'class'
match = '[Mm]pv'
icon = 'ï€ˆ'

[[icons.rules]]
property = 'class'
match = '[Vv]lc'
icon = 'ï©»'

[[icons.rules]]
property = 'class'
match = '[Ll]ibreoffice-writer'
icon = 'ï‡‚'

[[icons.rules]]
property = 'class'
match = '[Ll]ibreoffice-calc'
icon = 'ï‡ƒ'

[[icons.rules]]
property = 'class'
match = 'Peek'
icon = 'ï€½'

[[icons.rules]]
property = 'class'
match = 'ipython'
icon = 'îˆµ'

[[icons.rules]]
property = 'class'
match = 'python'
icon = 'îˆµ'

[[icons.rules]]
property = 'class'
match = 'jupyter-qtconsole'
icon = 'îˆµ'

[[icons.rules]]
property = 'class'
match = 'Gvim'
icon = 'îŸ…'

[[icons.rules]]
property = 'class'
match = 'settings'
icon = 'ï€“'

[[icons.rules]]
property = 'class'
match = 'slack'
icon = 'ï¦°'

[[icons.rules]]
property = 'class'
match = 'Zathura'
icon = 'ïœ¥'

[[icons.rules]]
property = 'class'
match = 'Telegram'
icon = 'îˆ•'

[[icons.rules]]
property = 'class'
match = 'Pavucontrol'
icon = 'ï©½'

[[icons.rules]]
property = 'class'
match = '\b.*\b'
icon = 'ï…¼'
